name: Remote Dispatch Action Initiator
 
on:
  push:
  schedule:
    - cron: '0 12 * * *'
  repository_dispatch:
 
jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: PING - Dispatch initiating repository event
        if: github.event.action != 'pong'
        run: |
          curl --location --request POST 'https://api.github.com/repos/vitaTiZ/secondWorkflows/dispatches' \
          --header 'Accept: application/vnd.github.everest-preview+json' \
          --header 'Authorization: Basic ${{ secrets.MY_ENV.ACCESS_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      - name: ACK - Acknowledge pong from remote repository
        if: github.event.action == 'pong'
        run: |
          echo "PONG received from '${{ github.event.client_payload.repository }}'" && \
          curl --location --request POST https://api.github.com/repos/vitaTiZ/secondWorkflows/dispatches \
          --header 'Accept: application/vnd.github.everest-preview+json' \
          --header 'Authorization: Basic ${{ secrets.MY_ENV.ACCESS_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{"event_type": "ack", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'