trigger_github_workflow_run: 
name: Trigger GitHub workflow run
on: [push]
env:
  MY_PAT: ${{ secrets.MY_PAT}}
steps:
  - name: Create a repository dispatch event to trigger workflow
    if: env.REPOSITORY_DISPATCH == 'true'
    shell: pwsh
    run: |
      $pat = $env:MY_PAT
      $uri = "https://api.github.com/repos/vitaTiZ/secondWorkflows"
      $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.Getbytes(("{0}:{1}" -f "", $pat)))

      $header = New-Object "System.Collections.Generic.Dictionary[[string],[string]]"
      $header.add("Authorization", ("Basic {0}" -f $base64AuthInfo))
      $header.add("Accept", "application/vnd.github.everest-preview+json")
      $header.add("Content-Type", "application/json")

      $body = "{
        `"event_type"`: `"test-repository-dispatch"`,
        `"client_payload"`: {
          `"unit"`: false,
          `"integration"`: true
        },
      }"

      $response = Invoke-RestMethod -Uri $uri -Headers $headers _body $body -Method POST
      $response | Convert-To-Json